# Automatic deployment to a staging environment on every push to master.
staging:
  auto_deploy_on: refs/heads/master
  required_contexts: ["build"]
  environment: staging
  description: 'Staging'
  payload:
    value_files: ["./config/staging.yml", "./config/_common.yml"]
    release: wss-bot
    namespace: wss-bot
    track: stable
    values:
      replicaCount: 1